/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author Admin
 */
public class GUI extends javax.swing.JFrame {

    public static double Add(double num1, double num2) {
        return num1 + num2;
    }

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    double num1, num2, num3, num4, result, a = 0, b = 0, c = 0, d = 0;
    String opr, letter, function;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        EquationClear = new javax.swing.JButton();
        PlusMinus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        point = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        ceilButton = new javax.swing.JButton();
        intButton = new javax.swing.JButton();
        moduloButton = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();
        squareRoot = new javax.swing.JToggleButton();
        cubeRoot = new javax.swing.JButton();
        Summation = new javax.swing.JButton();
        XY = new javax.swing.JButton();
        XYZ = new javax.swing.JButton();
        product = new javax.swing.JButton();
        doubleSummation = new javax.swing.JButton();
        doubleProduct = new javax.swing.JButton();
        set = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        logTwoX = new javax.swing.JButton();
        logX = new javax.swing.JButton();
        factorialAddition = new javax.swing.JButton();
        factorialDivision = new javax.swing.JButton();
        XTimesY = new javax.swing.JButton();
        XPlusY = new javax.swing.JButton();
        XRaisedY = new javax.swing.JButton();
        CTimesX = new javax.swing.JButton();
        XPlusC = new javax.swing.JButton();
        XRaisedC = new javax.swing.JButton();
        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        dLabel = new javax.swing.JLabel();
        functionName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        floorButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(560, 880));
        setMinimumSize(new java.awt.Dimension(560, 880));
        setPreferredSize(new java.awt.Dimension(570, 910));
        setResizable(false);
        setSize(new java.awt.Dimension(560, 890));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 520, 140));

        delete.setBackground(new java.awt.Color(0, 153, 204));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DEL");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 70));

        EquationClear.setBackground(new java.awt.Color(255, 51, 51));
        EquationClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EquationClear.setForeground(new java.awt.Color(255, 255, 255));
        EquationClear.setText("AC");
        EquationClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquationClearActionPerformed(evt);
            }
        });
        getContentPane().add(EquationClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, 70));

        PlusMinus.setBackground(new java.awt.Color(102, 102, 102));
        PlusMinus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PlusMinus.setForeground(new java.awt.Color(255, 255, 255));
        PlusMinus.setText("+/-");
        PlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(PlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 70, 70));

        plus.setBackground(new java.awt.Color(102, 102, 102));
        plus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, 70));

        seven.setBackground(new java.awt.Color(51, 51, 51));
        seven.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seven.setForeground(new java.awt.Color(255, 255, 255));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 70));

        eight.setBackground(new java.awt.Color(51, 51, 51));
        eight.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eight.setForeground(new java.awt.Color(255, 255, 255));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 70));

        nine.setBackground(new java.awt.Color(51, 51, 51));
        nine.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nine.setForeground(new java.awt.Color(255, 255, 255));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, 70));

        minus.setBackground(new java.awt.Color(102, 102, 102));
        minus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minus.setForeground(new java.awt.Color(255, 255, 255));
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, 70));

        four.setBackground(new java.awt.Color(51, 51, 51));
        four.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 70, 70));

        five.setBackground(new java.awt.Color(51, 51, 51));
        five.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 70, 70));

        six.setBackground(new java.awt.Color(51, 51, 51));
        six.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 70, 70));

        multiply.setBackground(new java.awt.Color(102, 102, 102));
        multiply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        multiply.setForeground(new java.awt.Color(255, 255, 255));
        multiply.setText("x");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 70, 70));

        one.setBackground(new java.awt.Color(51, 51, 51));
        one.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 70, 70));

        two.setBackground(new java.awt.Color(51, 51, 51));
        two.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 70, 70));

        three.setBackground(new java.awt.Color(51, 51, 51));
        three.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 70, 70));

        divide.setBackground(new java.awt.Color(102, 102, 102));
        divide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        divide.setForeground(new java.awt.Color(255, 255, 255));
        divide.setText("÷");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 70, 70));

        zero.setBackground(new java.awt.Color(51, 51, 51));
        zero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        zero.setForeground(new java.awt.Color(255, 255, 255));
        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 70, 70));

        point.setBackground(new java.awt.Color(102, 102, 102));
        point.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        point.setForeground(new java.awt.Color(255, 255, 255));
        point.setText(".");
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });
        getContentPane().add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 70, 70));

        equals.setBackground(new java.awt.Color(0, 153, 0));
        equals.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        equals.setForeground(new java.awt.Color(255, 255, 255));
        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });
        getContentPane().add(equals, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 140, 70));

        ceilButton.setBackground(new java.awt.Color(51, 51, 51));
        ceilButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ceilButton.setForeground(new java.awt.Color(255, 255, 255));
        ceilButton.setText("CEIL");
        ceilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceilButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ceilButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 70, 70));

        intButton.setBackground(new java.awt.Color(51, 51, 51));
        intButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        intButton.setForeground(new java.awt.Color(255, 255, 255));
        intButton.setText("INT");
        intButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intButtonActionPerformed(evt);
            }
        });
        getContentPane().add(intButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 70, 70));

        moduloButton.setBackground(new java.awt.Color(51, 51, 51));
        moduloButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        moduloButton.setForeground(new java.awt.Color(255, 255, 255));
        moduloButton.setText("%");
        moduloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduloButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moduloButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 70, 70));

        factorialButton.setBackground(new java.awt.Color(51, 51, 51));
        factorialButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        factorialButton.setForeground(new java.awt.Color(255, 255, 255));
        factorialButton.setText("N!");
        factorialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialButtonActionPerformed(evt);
            }
        });
        getContentPane().add(factorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 70, 70));

        squareRoot.setBackground(new java.awt.Color(51, 51, 51));
        squareRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        squareRoot.setForeground(new java.awt.Color(255, 255, 255));
        squareRoot.setText("√");
        squareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareRootActionPerformed(evt);
            }
        });
        getContentPane().add(squareRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 70, 70));

        cubeRoot.setBackground(new java.awt.Color(51, 51, 51));
        cubeRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cubeRoot.setForeground(new java.awt.Color(255, 255, 255));
        cubeRoot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/root.png"))); // NOI18N
        cubeRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeRootActionPerformed(evt);
            }
        });
        getContentPane().add(cubeRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 70, 70));

        Summation.setBackground(new java.awt.Color(51, 51, 51));
        Summation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Summation.setForeground(new java.awt.Color(255, 255, 255));
        Summation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/sumation.png"))); // NOI18N
        Summation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummationActionPerformed(evt);
            }
        });
        getContentPane().add(Summation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 70, 70));

        XY.setBackground(new java.awt.Color(51, 51, 51));
        XY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XY.setForeground(new java.awt.Color(255, 255, 255));
        XY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/expo.png"))); // NOI18N
        XY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYActionPerformed(evt);
            }
        });
        getContentPane().add(XY, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 70, 70));

        XYZ.setBackground(new java.awt.Color(51, 51, 51));
        XYZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XYZ.setForeground(new java.awt.Color(255, 255, 255));
        XYZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/double expo.png"))); // NOI18N
        XYZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XYZActionPerformed(evt);
            }
        });
        getContentPane().add(XYZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 70, 70));

        product.setBackground(new java.awt.Color(51, 51, 51));
        product.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product.setForeground(new java.awt.Color(255, 255, 255));
        product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/prod.png"))); // NOI18N
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 70, 70));

        doubleSummation.setBackground(new java.awt.Color(51, 51, 51));
        doubleSummation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doubleSummation.setForeground(new java.awt.Color(255, 255, 255));
        doubleSummation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/double sumation.png"))); // NOI18N
        doubleSummation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleSummationActionPerformed(evt);
            }
        });
        getContentPane().add(doubleSummation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 110, 70));

        doubleProduct.setBackground(new java.awt.Color(51, 51, 51));
        doubleProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        doubleProduct.setForeground(new java.awt.Color(255, 255, 255));
        doubleProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/double prod.png"))); // NOI18N
        doubleProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleProductActionPerformed(evt);
            }
        });
        getContentPane().add(doubleProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 110, 70));

        set.setBackground(new java.awt.Color(51, 51, 51));
        set.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        set.setForeground(new java.awt.Color(255, 255, 255));
        set.setText("SET");
        set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setActionPerformed(evt);
            }
        });
        getContentPane().add(set, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 280, 70));

        aButton.setBackground(new java.awt.Color(51, 51, 51));
        aButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aButton.setForeground(new java.awt.Color(255, 255, 255));
        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 70, 70));

        bButton.setBackground(new java.awt.Color(51, 51, 51));
        bButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bButton.setForeground(new java.awt.Color(255, 255, 255));
        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, 70, 70));

        cButton.setBackground(new java.awt.Color(51, 51, 51));
        cButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cButton.setForeground(new java.awt.Color(255, 255, 255));
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 70, 70));

        dButton.setBackground(new java.awt.Color(51, 51, 51));
        dButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dButton.setForeground(new java.awt.Color(255, 255, 255));
        dButton.setText("D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 70, 70));

        logTwoX.setBackground(new java.awt.Color(51, 51, 51));
        logTwoX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logTwoX.setForeground(new java.awt.Color(255, 255, 255));
        logTwoX.setText("log ₂ x");
        logTwoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logTwoXActionPerformed(evt);
            }
        });
        getContentPane().add(logTwoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 110, 70));

        logX.setBackground(new java.awt.Color(51, 51, 51));
        logX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logX.setForeground(new java.awt.Color(255, 255, 255));
        logX.setText("log x");
        logX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logXActionPerformed(evt);
            }
        });
        getContentPane().add(logX, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 630, 110, 70));

        factorialAddition.setBackground(new java.awt.Color(51, 51, 51));
        factorialAddition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        factorialAddition.setForeground(new java.awt.Color(255, 255, 255));
        factorialAddition.setText("a! + b!");
        factorialAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialAdditionActionPerformed(evt);
            }
        });
        getContentPane().add(factorialAddition, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 710, 110, 70));

        factorialDivision.setBackground(new java.awt.Color(51, 51, 51));
        factorialDivision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        factorialDivision.setForeground(new java.awt.Color(255, 255, 255));
        factorialDivision.setText("a! / b!");
        factorialDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(factorialDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 710, 110, 70));

        XTimesY.setBackground(new java.awt.Color(51, 51, 51));
        XTimesY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XTimesY.setForeground(new java.awt.Color(255, 255, 255));
        XTimesY.setText("x + y");
        XTimesY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XTimesYActionPerformed(evt);
            }
        });
        getContentPane().add(XTimesY, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 790, 70, 70));

        XPlusY.setBackground(new java.awt.Color(51, 51, 51));
        XPlusY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XPlusY.setForeground(new java.awt.Color(255, 255, 255));
        XPlusY.setText("x y");
        XPlusY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XPlusYActionPerformed(evt);
            }
        });
        getContentPane().add(XPlusY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 790, 70, 70));

        XRaisedY.setBackground(new java.awt.Color(51, 51, 51));
        XRaisedY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XRaisedY.setForeground(new java.awt.Color(255, 255, 255));
        XRaisedY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/xc.png"))); // NOI18N
        XRaisedY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XRaisedYActionPerformed(evt);
            }
        });
        getContentPane().add(XRaisedY, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 790, 70, 70));

        CTimesX.setBackground(new java.awt.Color(51, 51, 51));
        CTimesX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CTimesX.setForeground(new java.awt.Color(255, 255, 255));
        CTimesX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/sub.png"))); // NOI18N
        CTimesX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTimesXActionPerformed(evt);
            }
        });
        getContentPane().add(CTimesX, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 790, 70, 70));

        XPlusC.setBackground(new java.awt.Color(51, 51, 51));
        XPlusC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XPlusC.setForeground(new java.awt.Color(255, 255, 255));
        XPlusC.setText("x + C");
        XPlusC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XPlusCActionPerformed(evt);
            }
        });
        getContentPane().add(XPlusC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 790, 70, 70));

        XRaisedC.setBackground(new java.awt.Color(51, 51, 51));
        XRaisedC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        XRaisedC.setForeground(new java.awt.Color(255, 255, 255));
        XRaisedC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator/xc.png"))); // NOI18N
        XRaisedC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XRaisedCActionPerformed(evt);
            }
        });
        getContentPane().add(XRaisedC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 790, 70, 70));

        aLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        aLabel.setForeground(new java.awt.Color(51, 51, 51));
        aLabel.setText("A = 0");
        getContentPane().add(aLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, 50));

        bLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        bLabel.setForeground(new java.awt.Color(51, 51, 51));
        bLabel.setText("B = 0");
        getContentPane().add(bLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 50));

        cLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        cLabel.setForeground(new java.awt.Color(51, 51, 51));
        cLabel.setText("C = 0");
        getContentPane().add(cLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 50, 50));

        dLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        dLabel.setForeground(new java.awt.Color(51, 51, 51));
        dLabel.setText("D = 0");
        getContentPane().add(dLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, 50));

        functionName.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        functionName.setForeground(new java.awt.Color(51, 51, 51));
        functionName.setText("Function: ");
        getContentPane().add(functionName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 520, 140));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        floorButton.setBackground(new java.awt.Color(51, 51, 51));
        floorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        floorButton.setForeground(new java.awt.Color(255, 255, 255));
        floorButton.setText("FLR");
        floorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("//");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(floorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(floorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");

        opr = "+";
    }//GEN-LAST:event_plusActionPerformed

    private void PlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusMinusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        if (num1 > 0) {
            result = num1 * -1;
            jTextField1.setText(Double.toString(result));
        }

    }//GEN-LAST:event_PlusMinusActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "3");
    }//GEN-LAST:event_threeActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "0");
    }//GEN-LAST:event_zeroActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "2");
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "9");
    }//GEN-LAST:event_nineActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");

        opr = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");

        opr = "*";
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        jTextField1.setText("");

        opr = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(jTextField1.getText());
        num3 = Double.parseDouble(jTextField1.getText());

        if (opr == "+") {
            result = num1 + num2;
            jTextField1.setText(Double.toString(result));
        } else if (opr == "-") {
            result = num1 - num2;
            jTextField1.setText(Double.toString(result));
        } else if (opr == "*") {
            result = num1 * num2;
            jTextField1.setText(Double.toString(result));
        } else if (opr == "/") {
            result = num1 / num2;
            jTextField1.setText(Double.toString(result));
        } else if (opr == "mod") {
            result = num1 % num2;
            jTextField1.setText(Double.toString(result));
        }
    }//GEN-LAST:event_equalsActionPerformed

    private void EquationClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquationClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        aLabel.setText("A = 0");
        bLabel.setText("B = 0");
        cLabel.setText("C = 0");
        dLabel.setText("D = 0");
        functionName.setText("Function: ");

        a = 0;
        b = 0;
        c = 0;
        d = 0;
        function = "";
    }//GEN-LAST:event_EquationClearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        String backspace = null;

        if (jTextField1.getText().length() > 0) {
            StringBuilder s = new StringBuilder(jTextField1.getText());

            s.deleteCharAt(jTextField1.getText().length() - 1);
            backspace = s.toString();
            jTextField1.setText(backspace);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + ".");
    }//GEN-LAST:event_pointActionPerformed

    private void floorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        result = Math.floor(num1);
        jTextField1.setText(Double.toString(result));
    }//GEN-LAST:event_floorButtonActionPerformed

    private void ceilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceilButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        result = Math.ceil(num1);
        jTextField1.setText(Double.toString(result));
    }//GEN-LAST:event_ceilButtonActionPerformed

    private void intButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        int integer = (int) Math.floor(num1);
        jTextField1.setText(String.valueOf(integer));
    }//GEN-LAST:event_intButtonActionPerformed

    private void moduloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduloButtonActionPerformed
        // TODO add your handling code here:

        num1 = Double.parseDouble(jTextField1.getText());
        jTextField1.setText("");
        opr = "mod";
    }//GEN-LAST:event_moduloButtonActionPerformed

    private void factorialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialButtonActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        double product = 1;
        if (num1 < 0) {
            jTextField1.setText("Invalid Number");
        } else {
            for (double i = num1; i > 0; i--) {
                product = product * i;
                jTextField1.setText(Double.toString(product));
            }

        }
    }//GEN-LAST:event_factorialButtonActionPerformed

    private void squareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareRootActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(jTextField1.getText());

        double integer = Math.sqrt(num1);
        jTextField1.setText(String.valueOf(integer));
    }//GEN-LAST:event_squareRootActionPerformed

    private void SummationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummationActionPerformed
        double sum = 0;

        double x = Double.parseDouble(jTextField1.getText());

        if (function == "xa") {
            for (double i = a; i <= b; i++) {
                double term = x * i;
                sum = sum + term;
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x+a") {
            for (double i = a; i <= b; i++) {
                double term = x + i;
                sum = sum + term;
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x^a") {
            for (double i = a; i <= b; i++) {
                double term = Math.pow(x, i);
                sum = sum + term;
            }
            jTextField1.setText(String.valueOf(sum));
        }

    }//GEN-LAST:event_SummationActionPerformed

    private void XPlusYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XPlusYActionPerformed
        functionName.setText("Function: xa");
        function = "xa";
    }//GEN-LAST:event_XPlusYActionPerformed
    public static double factorial(Double num1) {
        double product = 1;

        for (double i = num1; i > 0; i--) {
            product = product * i;
        }

        return product;

    }
    private void factorialAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialAdditionActionPerformed
        double resultFactorialA = 0;
        double resultFactorialB = 0;
        double resultFactorial = 0;
        if (a != 0 && b != 0) {
            resultFactorialA = factorial(a);
            resultFactorialB = factorial(b);

            resultFactorial = resultFactorialA + resultFactorialB;

            jTextField1.setText(String.valueOf(resultFactorial));
        } else if (a == 0 && b != 0) {
            resultFactorialB = factorial(b);

            jTextField1.setText(String.valueOf(resultFactorialB));
        } else if (a != 0 && b == 0) {
            resultFactorialA = factorial(a);

            jTextField1.setText(String.valueOf(resultFactorialA));
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_factorialAdditionActionPerformed

    private void XPlusCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XPlusCActionPerformed
        functionName.setText("Function: x + C");
        function = "x+C";
    }//GEN-LAST:event_XPlusCActionPerformed

    private void XTimesYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XTimesYActionPerformed
        functionName.setText("Function: x + a");
        function = "x+a";
    }//GEN-LAST:event_XTimesYActionPerformed

    private void XRaisedYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XRaisedYActionPerformed
        functionName.setText("Function: x^a");
        function = "x^a";
    }//GEN-LAST:event_XRaisedYActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        a = Double.parseDouble(jTextField1.getText());
        letter = "A";
    }//GEN-LAST:event_aButtonActionPerformed

    private void setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setActionPerformed
        if (letter == "A") {
            aLabel.setText(String.valueOf("A = " + a));
        } else if (letter == "B") {
            bLabel.setText(String.valueOf("B = " + b));
        } else if (letter == "C") {
            cLabel.setText(String.valueOf("C = " + c));
        } else if (letter == "D") {
            dLabel.setText(String.valueOf("D = " + d));
        }

        jTextField1.setText("");
    }//GEN-LAST:event_setActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        b = Double.parseDouble(jTextField1.getText());
        letter = "B";
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        c = Double.parseDouble(jTextField1.getText());
        letter = "C";
    }//GEN-LAST:event_cButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        d = Double.parseDouble(jTextField1.getText());
        letter = "D";
    }//GEN-LAST:event_dButtonActionPerformed

    private void factorialDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialDivisionActionPerformed
        double resultFactorialA = 0;
        double resultFactorialB = 0;
        double resultFactorial = 0;
        if (a != 0 && b != 0) {
            resultFactorialA = factorial(a);
            resultFactorialB = factorial(b);

            resultFactorial = resultFactorialA / resultFactorialB;

            jTextField1.setText(String.valueOf(resultFactorial));
        } else if (a == 0 && b != 0) {
            resultFactorialB = factorial(b);

            jTextField1.setText(String.valueOf(resultFactorialB));
        } else if (a != 0 && b == 0) {
            resultFactorialA = factorial(a);

            jTextField1.setText(String.valueOf(resultFactorialA));
        } else {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_factorialDivisionActionPerformed

    private void logTwoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTwoXActionPerformed

        double result = Math.log(a) / Math.log(2);

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_logTwoXActionPerformed

    private void logXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logXActionPerformed
        double result = Math.log(a) / Math.log(10);

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_logXActionPerformed

    private void cubeRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeRootActionPerformed
        double num1 = Double.parseDouble(jTextField1.getText());

        double result = Math.cbrt(num1);

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_cubeRootActionPerformed

    private void CTimesXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTimesXActionPerformed
        functionName.setText("Function: Cx");
        function = "Cx";
    }//GEN-LAST:event_CTimesXActionPerformed

    private void XRaisedCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XRaisedCActionPerformed
        functionName.setText("Function: x^C");
        function = "x^C";
    }//GEN-LAST:event_XRaisedCActionPerformed

    private void XYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYActionPerformed
        double num1 = Double.parseDouble(jTextField1.getText());

        double result = Math.pow(num1, a);

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_XYActionPerformed

    private void XYZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XYZActionPerformed
        double num1 = Double.parseDouble(jTextField1.getText());

        double result = (Math.pow(num1, Math.pow(a, b)));

        jTextField1.setText(String.valueOf(result));
    }//GEN-LAST:event_XYZActionPerformed

    private void doubleSummationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleSummationActionPerformed
        double sum = 0;

        double x = Double.parseDouble(jTextField1.getText());

        if (function == "xa") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = x * i;
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x+a") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = x + i;
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x^a") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = Math.pow(x, i);
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "Cx") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = n * x;
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x+C") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = x + n;
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        } else if (function == "x^C") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    double term = Math.pow(x, n);
                    sum = sum + term;
                }
            }
            jTextField1.setText(String.valueOf(sum));
        }

    }//GEN-LAST:event_doubleSummationActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        double product = 1;

        double x = Double.parseDouble(jTextField1.getText());

        if (function == "xa") {
            for (double i = a; i <= b; i++) {
                double term = x * i;
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x+a") {
            for (double i = a; i <= b; i++) {
                double term = x + i;
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x^a") {
            for (double i = a; i <= b; i++) {
                double term = Math.pow(x, i);
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        }

    }//GEN-LAST:event_productActionPerformed

    private void doubleProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleProductActionPerformed
        double product = 1;
        double term = 0;

        double x = Double.parseDouble(jTextField1.getText());

        if (function == "xa") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    term = x * i;
                    product = product * term;
                }
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x+a") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    term = x + i;
                    product = product * term;
                }
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x^a") {
            for (double i = a; i <= b; i++) {
                for (double n = c; n <= d; n++) {
                    term = Math.pow(x, i);
                    product = product * term;
                }
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "Cx") {
            double condition = a + 1;
            for (double i = a; i <= b; i++) {
                term = 1;
                if (condition != i) {
                    for (double n = c; n <= d; n++) {
                        term = n * x;
                    }
                }
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x+C") {
            double condition = a + 1;
            for (double i = a; i <= b; i++) {
                term = 1;
                if (condition != i) {
                    for (double n = c; n <= d; n++) {
                        term = n + x;
                    }
                }
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        } else if (function == "x^C") {
            double condition = a + 1;
            for (double i = a; i <= b; i++) {
                term = 1;
                if (condition != i) {
                    for (double n = c; n <= d; n++) {
                        term = Math.pow(x, n);
                    }
                }
                product = product * term;
            }
            jTextField1.setText(String.valueOf(product));
        }
    }//GEN-LAST:event_doubleProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText() + "We are the Diligent Decoders");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CTimesX;
    private javax.swing.JButton EquationClear;
    private javax.swing.JButton PlusMinus;
    private javax.swing.JButton Summation;
    private javax.swing.JButton XPlusC;
    private javax.swing.JButton XPlusY;
    private javax.swing.JButton XRaisedC;
    private javax.swing.JButton XRaisedY;
    private javax.swing.JButton XTimesY;
    private javax.swing.JButton XY;
    private javax.swing.JButton XYZ;
    private javax.swing.JButton aButton;
    private javax.swing.JLabel aLabel;
    private javax.swing.JButton bButton;
    private javax.swing.JLabel bLabel;
    private javax.swing.JButton cButton;
    private javax.swing.JLabel cLabel;
    private javax.swing.JButton ceilButton;
    private javax.swing.JButton cubeRoot;
    private javax.swing.JButton dButton;
    private javax.swing.JLabel dLabel;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton doubleProduct;
    private javax.swing.JButton doubleSummation;
    private javax.swing.JButton eight;
    private javax.swing.JButton equals;
    private javax.swing.JButton factorialAddition;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton factorialDivision;
    private javax.swing.JButton five;
    private javax.swing.JButton floorButton;
    private javax.swing.JButton four;
    private javax.swing.JLabel functionName;
    private javax.swing.JButton intButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logTwoX;
    private javax.swing.JButton logX;
    private javax.swing.JButton minus;
    private javax.swing.JButton moduloButton;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton point;
    private javax.swing.JButton product;
    private javax.swing.JButton set;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JToggleButton squareRoot;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
